import re
from typing import Any, Dict, List, Optional
from core.evidence import _paragraphs, _clean_line, PROBLEM_SIGNAL_TERMS
from core.schemas import AREA_KEYWORDS, _keyword_occurrences, normalize_area
import string

try:
    from core.llm_provider import generate, test_connection
except ImportError:
    generate = None
    test_connection = None

BOILERPLATE_TERMS = (
    "greetings",
    "welcome",
    "copyright",
    "all rights reserved",
    "cookie policy",
    "privacy policy",
    "about us",
    "contact us",
    "subscribe",
    "newsletter",
    "sign up",
    "log in",
    "read more",
    "learn more",
    "click here",
    "terms of service",
    "navigation",
)

def _is_boilerplate(text: str) -> bool:
    lowered = text.lower()
    if len(text.split()) < 4:
        return True
    
    boilerplate_hits = sum(1 for term in BOILERPLATE_TERMS if term in lowered)
    if boilerplate_hits > 0 and len(text.split()) < 15:
        return True
    if boilerplate_hits > 2:
        return True
        
    return False

def _score_candidate(text: str, research_area: Optional[str] = None) -> Dict[str, Any]:
    lowered = text.lower()
    
    words = text.split()
    specificity_score = min(len(words) / 30.0, 1.0)
    
    limitation_terms = ("cannot", "fail", "limit", "latency", "bottleneck", "issue", "difficult", "impractical", "friction", "lack", "unable", "prevent", "require", "unreliable", "unresolved")
    researchability_score = sum(0.2 for term in PROBLEM_SIGNAL_TERMS if term in lowered)
    researchability_score += sum(0.3 for term in limitation_terms if term in lowered)
    researchability_score = min(researchability_score, 1.0)
    
    boilerplate_score = sum(0.2 for term in BOILERPLATE_TERMS if term in lowered)
    boilerplate_score = min(boilerplate_score, 1.0)
    area = normalize_area(research_area)
    area_signal_score = 0.0
    area_signal_count = 0
    if area in AREA_KEYWORDS:
        area_signal_count = sum(_keyword_occurrences(text, kw) for kw in AREA_KEYWORDS[area])
        area_signal_score = min(area_signal_count / 4.0, 1.0)
    
    return {
        "specificity_score": round(specificity_score, 2),
        "researchability_score": round(researchability_score, 2),
        "boilerplate_score": round(boilerplate_score, 2),
        "area_signal_score": round(area_signal_score, 2),
        "area_signal_count": area_signal_count,
    }

from typing import List
from core.research_schemas import ClaimValidation

def validate_claim_against_evidence(claim: str, evidence: List[str]) -> ClaimValidation:
    """
    Validates an arbitrary claim against a list of evidence spans.
    Fails if the claim contains facts (numbers/entities) not supported by the evidence.
    """
    import re
    words = re.findall(r'\b\w+\b', claim)
    evidence_lower = " ".join(evidence).lower()
    
    whitelist = {"problem", "challenge", "limitation", "bottleneck", "issue", "system", "current", "scalability", "performance", "requires", "cause", "causes", "create", "creates", "however", "therefore", "significant", "operational", "infrastructure", "verification", "transaction", "transactions", "latency", "high", "volume", "volumes", "scale", "bottlenecks", "limitations", "rises", "over", "above", "below", "associated", "increased", "increase", "decrease", "decreased"}
    
    for w in words:
        if not w: continue
        if w.isdigit():
            if w not in evidence_lower and w not in " ".join(evidence):
                return ClaimValidation(is_supported=False, score=0.0, reason=f"Unsupported number: {w}")
        if len(w) > 4:
            w_lower = w.lower()
            if w_lower not in whitelist and w_lower not in evidence_lower:
                if w_lower[:-1] not in evidence_lower and w_lower[:-2] not in evidence_lower:
                    return ClaimValidation(is_supported=False, score=0.0, reason=f"Unsupported entity: {w}")
    return ClaimValidation(is_supported=True, score=1.0, reason="All claim entities supported by evidence")

def _validate_refinement(refined_text: str, evidence_text: str) -> bool:
    """
    Determines whether an LLM refinement stays within the factual boundary of the original evidence.
    Args:
        refined_text: The compressed or refined statement generated by the LLM.
        evidence_text: The original source evidence text.
    """
    return validate_claim_against_evidence(refined_text, [evidence_text]).is_supported

def _refine_with_llm(candidate_problem: str, evidence: list[str]) -> str | None:
    if not generate:
        return None

    evidence_text = "\\n".join(evidence)
    prompt = f"""Refine the following candidate problem into a clear, concise, single-sentence research problem statement.
DO NOT introduce any new organizations, domains, populations, metrics, or technical capabilities that are not present in the evidence.

Evidence:
{evidence_text}

Candidate Problem:
{candidate_problem}

Output only the refined single-sentence problem statement, nothing else."""
    try:
        refined = generate(prompt)
        refined = refined.strip().strip('"').strip()
        if not refined or len(refined) < 10:
            return None
        
        if _validate_refinement(refined, evidence_text):
            return refined
    except Exception:
        pass
    return None

def _is_genuine_limitation(text: str) -> bool:
    t = text.strip().lower()
    strong = (
        r"\b(?:cannot|can't|fails?|failed|unable|lacks?|lacking|insufficient|limited|limitation|bottleneck|barrier|"
        r"unresolved|unknown|unclear|inadequate|impractical|fragile|unreliable|poor performance|"
        r"not (?:yet )?(?:possible|well understood|addressed|supported|solved)|remains a challenge|limits?|friction)\b"
    )
    if not re.search(strong, t):
        return False
    # Background/method boilerplate is rejected unless it contains an explicit
    # limitation signal. This preserves genuine sentences beginning with "The".
    if len(t.split()) < 6:
        return False
    if re.match(r"^(greetings|welcome|copyright|all rights reserved|please contact|we are thrilled)\b", t):
        return False
    return True

def _is_structured_problem_signal(text: str, *, title: str = "", research_area: Optional[str] = None, agent_name: Optional[str] = None) -> tuple[bool, str]:
    """Return whether a source-framed sentence is itself a problem/challenge signal.

    Some high-value collection layers state the problem structurally rather than with
    limitation vocabulary (e.g. ``Challenge track: build ...`` or ``Incident report: ...``).
    This helper only promotes sentences whose *source framing* explicitly identifies the
    sentence as a challenge, incident, benchmark need, gap, or required capability. It
    therefore broadens recall without turning arbitrary descriptive prose into a problem.
    """
    t = text.strip()
    low = t.lower()
    agent = (agent_name or "").strip().lower()
    area = normalize_area(research_area) or ""

    framed_prefixes = (
        ("challenge track:", "challenge_statement"),
        ("challenge:", "challenge_statement"),
        ("problem statement:", "problem_statement"),
        ("problem:", "problem_statement"),
        ("incident report:", "incident"),
        ("root cause:", "root_cause"),
        ("dataset and benchmark description:", "benchmark_need"),
        ("benchmark description:", "benchmark_need"),
        ("research gap:", "research_gap"),
        ("known gap:", "research_gap"),
        ("ecosystem need:", "ecosystem_need"),
        ("technical challenge:", "technical_challenge"),
    )
    for prefix, kind in framed_prefixes:
        if low.startswith(prefix) and len(t.split()) >= 7:
            return True, kind

    # Collector-specific source framing is intentionally narrow. These patterns are
    # common in the corresponding source classes and require a substantive payload.
    if agent == "hackathon" and re.match(r"^(track|bounty)\b", low) and any(v in low for v in ("build ", "create ", "develop ", "implement ")):
        return True, "challenge_statement"
    if agent == "failure" and any(k in low for k in ("incident", "failure mode", "outage", "depeg", "cascade")) and any(v in low for v in ("triggered", "caused", "resulted", "led to")):
        return True, "incident"
    if agent == "data_availability" and any(k in low for k in ("dataset", "benchmark", "simulator", "benchmark suite")) and any(k in low for k in ("latency", "reproducible", "evaluation", "experiment", "metric")):
        return True, "benchmark_need"

    return False, ""

def extract_problem_intelligence(content: str, title: str, evidence_bundle: dict, *, allow_llm_refinement: bool = True, research_area: Optional[str] = None, agent_name: Optional[str] = None) -> dict:
    paragraphs = _paragraphs(content)
    
    candidates = []
    
    for para in paragraphs:
        if _is_boilerplate(para):
            continue
            
        scores = _score_candidate(para, research_area)
        if scores["boilerplate_score"] >= 0.6:
            continue
            
        limitation = _is_genuine_limitation(para)
        structured, structured_type = _is_structured_problem_signal(
            para, title=title, research_area=research_area, agent_name=agent_name
        )
        if limitation or structured:
            problem_type = "identified_limitation" if limitation else structured_type
            candidates.append({
                "problem": para[:300].strip(),
                "problem_type": problem_type,
                "evidence": [para],
                "evidence_refs": [],
                "specificity_score": scores["specificity_score"],
                "researchability_score": scores["researchability_score"],
                "boilerplate_score": scores["boilerplate_score"],
                "area_signal_score": scores["area_signal_score"],
                "area_signal_count": scores["area_signal_count"],
                "confidence": (
                    "High" if structured and scores["specificity_score"] >= 0.4
                    else "Medium" if structured or scores["researchability_score"] >= 0.4
                    else "Low"
                )
            })
            
    if normalize_area(research_area) in AREA_KEYWORDS:
        candidates.sort(key=lambda c: (c["area_signal_score"], c["researchability_score"], c["specificity_score"], -c["boilerplate_score"]), reverse=True)
    else:
        candidates.sort(key=lambda c: (c["researchability_score"], c["specificity_score"], -c["boilerplate_score"]), reverse=True)
    candidates = candidates[:5]
    
    intelligence_mode = "deterministic"
    
    selected_problem = None
    problem_type = None
    problem_evidence = []
    problem_confidence = "Low"
    
    if candidates:
        best = candidates[0]
        selected_problem = best["problem"]
        problem_type = best["problem_type"]
        problem_evidence = best["evidence"]
        problem_confidence = best["confidence"]
        
    original_candidate = selected_problem
    if allow_llm_refinement and generate and test_connection and selected_problem:
        try:
            refined = _refine_with_llm(selected_problem, problem_evidence)
            if refined:
                selected_problem = refined
                intelligence_mode = "llm_assisted"
        except Exception:
            pass

    if not original_candidate:
        selected_problem = None
        problem_type = "unresolved"
        problem_confidence = "None"
        problem_evidence = []
        
    if selected_problem is not None:
        assert len(problem_evidence) >= 1, "Invariant failed: selected_problem must have >= 1 evidence"
        if intelligence_mode == "deterministic":
            found_in_content = any(selected_problem in ev for ev in problem_evidence) or selected_problem in content
            assert found_in_content, "Invariant failed: selected_problem must correspond to actual source text"

    return {
        "problem_candidates": candidates,
        "selected_problem": selected_problem,
        "original_candidate": original_candidate,
        "problem_type": problem_type,
        "problem_evidence": problem_evidence,
        "problem_confidence": problem_confidence,
        "intelligence_mode": intelligence_mode
    }
